project:
  type: website

website:
  title: "Brileigh Cates' Professional Website"
  navbar:
    logo-href: opening.qmd
    left:
      - href: opening.qmd
        text: "Home"
      - href: research.qmd
        text: "Research Interests & Projects"
      - href: CV.qmd
        text: "CV"
      - href: ContactInfo.qmd
        text: "Contact Information"
        
resources:
  - BCatesCV.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

